version: "3.9"

services:

  sql_db:
    image: mysql:8
    container_name: sql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_PASSWORD=jim
      - MYSQL_ROOT_PASSWORD=jim
      - MYSQL_USER=jim
      - MYSQL_DATABASE=currency
    networks:
      - currency-network
   
   
  currency-exchange:
    image:  n9064/microservice-course12:1.0.0-SNAPSHOT
    container_name: currency-exchange
    ports: 
       - "8000:8000"
    depends_on:      
       - sql_db
    networks:
      - currency-network
    environment:
      - SPRING_DATASOURCE_USERNAME=jim
      - SPRING_DATASOURCE_URL=jdbc:mysql://sql_db:3306/currency
      - SPRING_DATASOURCE_PASSWORD=jim
   
networks:
  currency-network:
    driver: bridge