version: "3.9"

services:

  sql_db:
    image: mysql:8
    container_name: sql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_PASSWORD=jim
      - MYSQL_ROOT_PASSWORD=jim
      - MYSQL_USER=jim
      - MYSQL_DATABASE=currency
    networks:
      - currency-network
    healthcheck:
      test: mysql curency --user=jim --password=jim --silent --execute "show database;"
      interval: 30s
      timeout: 10s
      retries: 5      
    
  currency-exchange:
    image:  n9064/m-currency-exchange-service:0.0.1-SNAPSHOT
    container_name: currency-exchange
    ports: 
       - "8000:8000"
    depends_on:
     sql_db:
       condition: service_healthy
     naming-server:
       condition: service_started
    networks:
      - currency-network
    environment:
      - SPRING_DATASOURCE_USERNAME=jim
      - SPRING_DATASOURCE_URL=jdbc:mysql://sql_db:3306/currency
      - SPRING_DATASOURCE_PASSWORD=jim
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://naming-server:8761/eureka
   
  
  naming-server:
   image: n9064/msa-netflix-eureka-naming-server:0.0.1-SNAPSHOT
   container_name: naming-server
   ports:
      - "8761:8761"
   networks:
      - currency-network 
   
networks:
  currency-network:
    driver: bridge